version: "3.8"
services:
  nginx:
    ports:
      - "4000:80"
  app:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_USER=rootusername
      - MONGO_PASSWORD=rootpassword
      - SESSION_SECRET=sessionsecret
    command: npm run dev
